services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    container_name: trsapp_backend
    volumes:
      - ./backend:/rails
      - ./backend/tmp:/rails/tmp
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: ${SUPABASE_DB_URL}
      ALLOWED_EXTERNAL_HOSTS: ${SUPABASE_DB_HOST}
      SUPABASE_DB_USER: ${SUPABASE_DB_USER}
      SUPABASE_DB_PASSWORD: ${SUPABASE_DB_PASSWORD}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      SUPABASE_JWT_SECRET: ${SUPABASE_JWT_SECRET}
    networks:
      - internal_network
      - default


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: trsapp_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
      VITE_SUPABASE_URL: ${SUPABASE_URL}
      VITE_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
    depends_on:
      - backend

networks:
  internal_network: 
    internal: false
    enable_ipv6: true
volumes:
  db-data:
